#!/bin/bash -e

# Set the PYTHONPATH
echo 'export PYTHONPATH="/home/dotcloud/current/src:/home/dotcloud/current/lib"' >> ~/.profile

# Re-source the profile to get the new value
source ~/.profile

# Ensure DB is created an setup/migrated
cd ~/current/scripts
if [ "$1" == "worker" ]; then
    python createdb.py
    django-admin.py syncdb --noinput
    django-admin.py migrate
    mv ~/current/supervisord.worker.conf ~/current/supervisord.conf
fi

if [ "$1" == "www" ]; then
    django-admin.py collectstatic --noinput -i coffeescript
fi